package pe.laramadita.seguridad.config;
import java.nio.charset.StandardCharsets; import javax.crypto.spec.SecretKeySpec;
import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.*; import org.springframework.http.MediaType; import org.springframework.security.authentication.*; import org.springframework.security.authentication.dao.DaoAuthenticationProvider; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.oauth2.jose.jws.MacAlgorithm; import org.springframework.security.oauth2.jwt.*; import org.springframework.security.web.SecurityFilterChain; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
import pe.laramadita.seguridad.service.UsuarioDetailsService;
@Configuration @EnableMethodSecurity
public class SecurityConfig{
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean JwtEncoder jwtEncoder(@Value("${app.security.jwt-secret}") String secret){return new NimbusJwtEncoder(new com.nimbusds.jose.jwk.source.ImmutableSecret<>(clave(secret)));}
 @Bean JwtDecoder jwtDecoder(@Value("${app.security.jwt-secret}") String secret){return NimbusJwtDecoder.withSecretKey(clave(secret)).macAlgorithm(MacAlgorithm.HS256).build();}
 private SecretKeySpec clave(String secret){return new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256");}
 @Bean AuthenticationManager authenticationManager(UsuarioDetailsService uds,PasswordEncoder encoder){var p=new DaoAuthenticationProvider();p.setUserDetailsService(uds);p.setPasswordEncoder(encoder);return new ProviderManager(p);}
 @Bean SecurityFilterChain chain(HttpSecurity http,JwtAuthenticationFilter jwt)throws Exception{return http.csrf(c->c.disable()).cors(c->{}).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/v1/auth/login","/error").permitAll().anyRequest().authenticated()).exceptionHandling(e->e.authenticationEntryPoint((req,res,x)->{res.setStatus(401);res.setContentType(MediaType.APPLICATION_PROBLEM_JSON_VALUE);res.getWriter().write("{\"title\":\"No autenticado\",\"status\":401,\"detail\":\"Se requiere iniciar sesión\"}");}).accessDeniedHandler((req,res,x)->{res.setStatus(403);res.setContentType(MediaType.APPLICATION_PROBLEM_JSON_VALUE);res.getWriter().write("{\"title\":\"Acceso denegado\",\"status\":403,\"detail\":\"No tiene permiso para realizar esta operación\"}");})).addFilterBefore(jwt,UsernamePasswordAuthenticationFilter.class).build();}
}
